### ISSUE TITLE
Am I supposed to get node groups added too after running it?

### ISSUE THREAD

**Issue by taragurung** [quickbooks2018/Terraform-V-12#5]
Though I see this section in main.tf of eks module the node groups are not added. I hope this module is for creating node group which it does not If I am not wrong.

```
module "eks_workers" {
}
```

**Comment by ch-muhammad-asim** [comment]
https://github.com/quickbooks2018/Terraform-V-12/blob/master/terraform.v12/eks/environment/dev/main.tf


EKS Workers are node_group,(worker nodes) which is auto-scaling, simply change the desired min max size, please subscribe, share my Youtube Channel.  

https://www.youtube.com/c/AWSLinuxWindows
