### ISSUE TITLE
VPC output function is not working

### ISSUE THREAD

**Issue by devopsdymyr** [quickbooks2018/Terraform-V-12#6]
Reference to undeclared module

  on ../../modules/aws-vpc/output.tf line 6, in output "vpc-id":

# Output of VPC

output "vpc-id" {
  description = "The ID of the VPC"
  value       = concat(aws_vpc.vpc.*.id, [""])[0]

}

**Comment by ch-muhammad-asim** [comment]
Issue is fixed

**Comment by ch-muhammad-asim** [comment]
I have updated the code, if you face any issue let me know
